config/routes.rb
Gg::Application.routes.draw do

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :customers
  resources :suppliers
  resources :products
  resources :categories
  resources :vats
  resources :items
  resources :invoices
  resources :banks
  resources :checks
  resources :locations
  resources :receipts
  resources :cards

  resources :documents do
    collection do
      get 'options'
    end
  end

  get '/landing_page', to: 'landing#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/bank.rb
class Bank < ActiveRecord::Base
  attr_accessible :name, :branch_office_number, :address ,:location_id

  # ==validations
  validates_presence_of :name, :branch_office_number, :address, :location
  validate :not_exist_same

  belongs_to :location

  # == Callbacks
  before_save :name_upcase

  def not_exist_same
    if Bank.where("name= ? AND branch_office_number = ?",self.name, self.branch_office_number).exists?
      errors.add(:complete_name,I18n.t('activerecord.models.errors.message_bank_insert'))
    end
  end

  def name_upcase
    self.name = self.name.upcase
  end

  def complete_name
    "#{name} (#{branch_office_number})"
  end
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController

  respond_to :html, :json
  before_filter :authenticate_user!

  def new
    @bank = Bank.new
    if request.xhr?
      render partial: 'new_bank_modal'
    end  
  end

  def create
    @bank = Bank.new(params[:bank])
    @bank.save
    respond_to do |format|
      format.json { render json: @bank }
    end  
  end

  def show
    @bank = Bank.find(params[:id])
  end

  def edit
    @bank = Bank.find(params[:id])
  end

  def update
    @bank = Bank.find(params[:id])
    if @bank.update_attributes(params[:bank])
      flash[:success] = t('flash.bank', message: t('flash.updated'))
    end
    respond_with @bank
  end

end

app/helpers/banks_helper.rb
module BanksHelper
end

app/views/banks/_bank_data.html.haml
.data-bank
  .left
    .title= t('banks.bank_data')
    .input
      = f.label :name
      = f.collection_select :name,
                            Bank.all,
                            :name, :name,
                            { :include_blank => true}, class: "pretty-input"
      %a#openBtn-bank-name
        %i.icon-plus-sign.icon-1x
    .input
      = f.label :branch_office_number
      = f.text_field :branch_office_number, class: "pretty-input"
    .input
      = f.label :address
      = f.text_field :address, class: "pretty-input"
    .input
      = f.label :location
      = f.collection_select :location_id,
                            Location.all,
                            :id, :complete_name,
                            { :include_blank => true }, class: "pretty-input"
      %a#openBtn-location
        %i.icon-plus-sign.icon-1x
  .right

app/views/banks/_new_bank_modal.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", type: "button"} ×
      %h3= t('.new_bank')
    = form_for(Bank.new, remote: true, format: :json ) do |f|
      = errors_for(@bank).html_safe
      .modal-body
        .input
          = f.label :name
          = f.text_field :name, class: "pretty-input"
        .input
          = f.label :branch_office_number
          = f.text_field :branch_office_number, class: "pretty-input"
        .input
          = f.label :address
          = f.text_field :address, class: "pretty-input"
        .input
          = f.label :location
          = f.collection_select :location_id,
                                Location.all,
                                :id, :complete_name,
                                { :include_blank => true }, class: "pretty-input"
      .modal-footer
        = f.submit t('.save'), class: 'modal-submit'

app/views/banks/_new_location.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", type: "button"} ×
      %h3= t('.new_location')
    -locat =  Location.new
    = form_for(locat, remote: true, format: :json ) do |c|
      .error#error
      .modal-body
        .input
          = c.label :city
          = c.text_field :city, class: "pretty-input"
        .input
          = c.label :state
          = c.text_field :state, class: "pretty-input"
        .input
          = c.label :countri
          = c.text_field :countri, class: "pretty-input"
      .modal-footer
        = c.submit t('.save'), class: "btn-modal-submit"

app/views/banks/_new_name.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", type: "button"} ×
      %h3= t('.new_name')
    .modal-body
      .input
        = label_tag t('.name')
        = text_field_tag 'new-name-bank',nil, class: "pretty-input"
    .modal-footer
      = submit_tag t('.add'),id: "add-new-name", class: "btn-modal-submit"

app/views/banks/_show_bank_data.html.haml
.show-bank
  .left
    .title= t('.bank_data')
    .input
      = label_tag t('activerecord.attributes.bank.name')
      = label_tag @bank.name, nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.bank.branch_office_number')
      = label_tag @bank.branch_office_number, nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.bank.address')
      = label_tag @bank.address, nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.bank.location')
      = label_tag @bank.location.complete_name, nil, class: "pretty-input"
  .right

app/views/banks/_sub_header.html.haml
#banks
  .sub-header
    -if edit_or_new_page?(@bank)
      %a.bank-save
        %i.icon-save.icon-2x
        = t('.save')
      %a.bank-danger{href: "#{banks_path}"}
        %i.icon-remove-sign.icon-2x
        = t('.cancel')
    -elsif show_page?(@bank)
      %a.bank-new{ href: "#{edit_bank_path(@bank)}" }
        %i.icon-edit.icon-2x
        = "editar"
    -else
      %a.bank-new{ href: "#{new_bank_path}" }
        %i.icon-plus-sign.icon-2x
        = t('.new')
      %a.bank-print{href: "#"}
        %i.icon-print.icon-2x
        = t('.print')

app/views/banks/edit.html.haml
#banks
  %ul.bank-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#bank-data"}
        = t('banks.bank')
  = form_for @bank do |f|
    = errors_for(@bank).html_safe
    .tab-content
      .tab-pane.active#bank-data
        = render "bank_data", f: f
    = f.submit hidden: true

  #bank-modal.modal.fade
    = render "new_name"
  #location-modal.modal.fade
    = render "new_location"

app/views/banks/new.html.haml
#banks
  %ul.bank-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#bank-data"}
        = t('banks.bank')
  = form_for @bank do |f|
    = errors_for(@bank).html_safe
    .tab-content
      .tab-pane.active#bank-data
        = render "bank_data", f: f
    = f.submit hidden: true

  #bank-modal.modal.fade
    = render "new_name"
  #location-modal.modal.fade
    = render "new_location"

app/views/banks/show.html.haml
#banks
  %ul.bank-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#bank-data"}
        = t('.bank_data')
  .tab-content
    .tab-pane.active#bank-data
      = render "show_bank_data"