config/routes.rb
Gg::Application.routes.draw do

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :customers
  resources :suppliers
  resources :products
  resources :categories
  resources :vats
  resources :items
  resources :invoices
  resources :banks
  resources :checks
  resources :locations
  resources :receipts
  resources :cards

  resources :documents do
    collection do
      get 'options'
    end
  end

  get '/landing_page', to: 'landing#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/check.rb
class Check < ActiveRecord::Base

  # == Accesors
  attr_accessible :check_number , :account, :emission_date, :payment_date, 
                  :emisor, :amount, :check_status ,:is_proper ,:bank_id,
                  :document_id, :annul


  # ==validations
  validates_presence_of :check_number, :emisor, :amount, :emission_date, 
                        :payment_date
  validate :correct_date

  # ==Associations
  belongs_to :bank
  belongs_to :document

  def correct_date
    if emission_date > payment_date
      errors.add(:emission_date, I18n.t('activerecord.models.errors.message_check_date'))
    end
  end

end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController

  respond_to :html, :json
  before_filter :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.json { render json: ChecksDatatable.new(view_context) }
    end
  end

  def new
    @check = Check.new
    if request.xhr?
      render partial: 'new_check'
    end
  end

  def create
    @check = Check.new(params[:check])
    @check.save
    respond_to do |format|
      format.html { render partial: "new_check_row" }
      format.json { render json: @check }
      format.js
    end
  end

  def show
    @check = Check.find(params[:id])  
  end

  def edit
    @check = Check.find(params[:id])
    if request.xhr?
      render partial: 'update_check'
    end
  end

  def update
    @check = Check.find(params[:id])
    if @check.update_attributes(params[:check])
      respond_to do |format|
        format.html { render partial: "new_check_row" }
        format.json { render json: @check }
        format.js
      end
    end   
  end

  def destroy
    ids = params[:id].split(",")
    ids.map { |c| Check.find(c).destroy }
    respond_with @check
  end
  
end

app/helpers/checks_helper.rb
module ChecksHelper

 STATUS = %w{in_folder returned charged}

 def check_status
    STATUS.map{ |s| [I18n.t(".checks.status.#{s}"), I18n.t(".checks.status.#{s}")] }
 end

 def link_bank(bank)
    path, link = "",""
    if bank.present?
      path =  bank_path(bank)
      link = bank.complete_name.truncate(45)
      link_to link, path, class: "note"
    else
      label_tag ""
    end
  end


end

app/views/checks/_check_data.html.haml
.data-check
  .left
    .title= t('checks.check_data')
    .input
      = f.label :amount
      = f.number_field :amount, class: "pretty-input"
    .input
      = f.label :check_number
      = f.text_field :check_number, class: "pretty-input"
    .input
      = f.label :emission_date
      .check_date_time_picker
        = f.text_field :emission_date, { class: "pretty-input",
                                      value: print_date(f.object.emission_date, :date_human) }
        %span.input-group-addon.glyphicon.glyphicon-calendar
    .input
      = f.label :payment_date
      .check_date_time_picker
        = f.text_field :payment_date, { class: "pretty-input",
                                    value: print_date(f.object.payment_date, :date_human) }
        %span.input-group-addon.glyphicon.glyphicon-calendar
  .right
    .title= t('checks.comercial_data')
    .input
      = f.label :emisor
      = f.text_field :emisor, class: "pretty-input"
    .input
      = f.label :account
      = f.text_field :account, class: "pretty-input"
    .input
      = f.label :bank
      = f.collection_select :bank_id,
                            Bank.all,
                            :id, :complete_name,
                            { :include_blank => true }, class: "pretty-input"
      %a#openBtn-bank{href: "#{new_bank_path}", class: current_tag('checks')}
        %i.icon-plus-sign.icon-1x
    .input
      = f.label :check_status
      = f.select :check_status, check_status,
                          { :include_blank => true }, class: "pretty-input"

app/views/checks/_new_check.html.haml
.data-check
  = form_for(Check.new, remote: true, format: :html) do |f|
    .left
      .title= t('checks.check_data')
      .input
        = f.label :amount
        = f.number_field :amount, class: "pretty-input"
      .input
        = f.label :check_number
        = f.text_field :check_number, class: "pretty-input"
      .input
        = f.label :emission_date
        .check_date_time_picker
          = f.text_field :emission_date, { class: "pretty-input",
                                        value: print_date(f.object.emission_date, :date_human) }
          %span.input-group-addon.glyphicon.glyphicon-calendar
      .input
        = f.label :payment_date
        .check_date_time_picker
          = f.text_field :payment_date, { class: "pretty-input",
                                      value: print_date(f.object.payment_date, :date_human) }
          %span.input-group-addon.glyphicon.glyphicon-calendar
    .right
      .title= t('checks.comercial_data')
      .input
        = f.label :emisor
        = f.text_field :emisor, class: "pretty-input"
      .input
        = f.label :account
        = f.text_field :account, class: "pretty-input"
      .input
        = f.label :bank
        = f.collection_select :bank_id,
                              Bank.all,
                              :id, :complete_name,
                              { :include_blank => true }, class: "pretty-input"
        %a#openBtn-bank
          %i.icon-plus-sign.icon-1x
      .input
        = f.label :check_status
        = f.select :check_status, check_status,
                            { :include_blank => true }, class: "pretty-input"
      .input
        %a.button-save
          %i.icon-save.icon-1x
            = t('.save')              
    = f.submit hidden: true
    

app/views/checks/_new_check_row.html.haml
%tr{"data-check-id" => @check.id}
  %td= @check.check_number
  %td= @check.emisor
  %td= @check.emission_date
  %td= @check.payment_date
  %td= @check.amount
  %td= @check.check_status
  %td
    %a.button-show{ href: @check }
      = t('.show')
    / %a.button-edit{ onclick: "editCheck(this)" }
    /   = t('.edit')
    %a.button-delete{ id: "delete-check", onclick: "deleteRow(this)" }  
      = t('.delete')
%input{id: "check-amount", type: "hidden", value: @check.amount}
%input{id: "check-update-id", type: "hidden", value: @check.id}  

app/views/checks/_show_check_data.html.haml
.show-check
  .left
    .title= t('checks.check_data')
    .input
      = label_tag t('activerecord.attributes.check.amount')
      = label_tag @check.amount,nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.check.check_number')
      = label_tag @check.check_number, nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.check.emission_date')
      = label_tag print_date(@check.emission_date, :date_human) ,nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.check.payment_date')
      = label_tag print_date(@check.payment_date, :date_human) ,nil, class: "pretty-input"
  .right
    .title= t('checks.comercial_data')
    .input
      = label_tag t('activerecord.attributes.check.emisor')
      = label_tag @check.emisor, nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.check.account')
      = label_tag @check.account, nil, class: "pretty-input"
    .input
      = label_tag t('activerecord.attributes.check.bank')
      = link_bank(@check.bank)
    .input
      = label_tag t('activerecord.attributes.check.check_status')
      = label_tag @check.check_status, nil, class: "pretty-input"

app/views/checks/_sub_header.html.haml
#checks
  .sub-header
    -if edit_or_new_page?(@check)
      %a.check-save
        %i.icon-save.icon-2x
        = t('.save')
      %a.check-danger{href: "#{checks_path}"}
        %i.icon-remove-sign.icon-2x
        = t('.cancel')
    -elsif show_page?(@check)
      %a.check-new{ href: "#{edit_check_path(@check)}" }
        %i.icon-edit.icon-2x
        = "editar"
    -else
      %a.check-new{ href: "#{new_check_path}" }
        %i.icon-plus-sign.icon-2x
        = t('.new')
      %a.check-print{href: "#"}
        %i.icon-print.icon-2x
        = t('.print')

app/views/checks/_update_check.html.haml
.data-check
  = form_for(@check, remote: true, format: :html) do |f|
    .left
      .title= t('checks.check_data')
      .input
        = f.label :amount
        = f.number_field :amount, class: "pretty-input"
      .input
        = f.label :check_number
        = f.text_field :check_number, class: "pretty-input"
      .input
        = f.label :emission_date
        .check_date_time_picker
          = f.text_field :emission_date, { class: "pretty-input",
                                        value: print_date(f.object.emission_date, :date_human) }
          %span.input-group-addon.glyphicon.glyphicon-calendar
      .input
        = f.label :payment_date
        .check_date_time_picker
          = f.text_field :payment_date, { class: "pretty-input",
                                      value: print_date(f.object.payment_date, :date_human) }
          %span.input-group-addon.glyphicon.glyphicon-calendar
    .right
      .title= t('checks.comercial_data')
      .input
        = f.label :emisor
        = f.text_field :emisor, class: "pretty-input"
      .input
        = f.label :account
        = f.text_field :account, class: "pretty-input"
      .input
        = f.label :bank
        = f.collection_select :bank_id,
                              Bank.all,
                              :id, :complete_name,
                              { :include_blank => true }, class: "pretty-input"
        %a#openBtn-bank
          %i.icon-plus-sign.icon-1x
      .input
        = f.label :check_status
        = f.select :check_status, check_status,
                            { :include_blank => true }, class: "pretty-input"
      .input
        %a.button-update
          %i.icon-save.icon-1x
            = t('.save')           
    = f.submit hidden: true
       

app/views/checks/edit.html.haml
#checks
  %ul.check-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#check-data"}
        = t('checks.check')
  = form_for @check do |f|
    = errors_for(@check).html_safe
    .tab-content
      .tab-pane.active#check-data
        = render "check_data", f: f
    = f.submit hidden: true

app/views/checks/index.html.haml
#checks
  %table#checks-table.display{"data-source" => checks_url(format:"json")}
    %thead
      %tr
        %th
        %th
        %th
        %th= select_tag nil,
                        options_from_collection_for_select(Bank.all, "id", "complete_name"),
                        {include_blank: true ,class: "pretty-input-data-table"}
        %th= text_field_tag nil, nil,class: "pretty-input-data-table",id: 'emission_date',
                            type: "text",
                            name: "daterange",
                            placeholder: t('.last_date')
        %th= text_field_tag nil, nil,class: "pretty-input-data-table", id: 'payment_date',
                            type: "text",
                            name: "daterange",
                            placeholder: t('.last_date')
        %th= select_tag nil, options_for_select(check_status), {include_blank: true ,class: "pretty-input-data-table"}
      %tr
        %th=t('activerecord.attributes.check.check_number')
        %th=t('activerecord.attributes.check.account')
        %th=t('activerecord.attributes.check.emisor')
        %th=t('activerecord.attributes.check.bank')
        %th=t('activerecord.attributes.check.emission_date')
        %th=t('activerecord.attributes.check.payment_date')
        %th=t('activerecord.attributes.check.check_status')
    %tbody
    %tfoot

app/views/checks/new.html.haml
#checks
  %ul.check-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#check-data"}
        = t('checks.check')
  = form_for @check do |f|
    = errors_for(@check).html_safe
    .tab-content
      .tab-pane.active#check-data
        = render "check_data", f: f
    = f.submit hidden: true

  / #check-modal.modal.fade
  /   = render "new_name"

app/views/checks/show.html.haml
#checks
  %ul.check-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#check-data"}
        = t('.check_data')
  .tab-content
    .tab-pane.active#check-data
      = render "show_check_data"