config/routes.rb
Gg::Application.routes.draw do

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  resources :customers
  resources :suppliers
  resources :products
  resources :categories
  resources :vats
  resources :items
  resources :invoices
  resources :banks
  resources :checks
  resources :locations
  resources :receipts
  resources :cards

  resources :documents do
    collection do
      get 'options'
    end
  end

  get '/landing_page', to: 'landing#index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  ActiveAdmin.routes(self)
end

app/models/category.rb
class Category < ActiveRecord::Base

  # == Accesors
  attr_accessible :name, :referrer, :referrer_id
  attr_reader :referrer_id

  # == Associations
  belongs_to :referrer, :class_name => 'Category'
  has_many :referrals, :foreign_key => :referrer_id,
                       :class_name  => 'Category'
  has_and_belongs_to_many :products

  # == Validations
  validates_presence_of :name
  validates_uniqueness_of :name

  # == Scope
  scope :root, -> {where(referrer_id: nil)}


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  respond_to :html, :json
  before_filter :authenticate_user!


  def index
    respond_to do |format|
      format.html { render html: @categories =Category.all}
      format.json { render json: Category.where(
                                    "categories.name ILIKE ?",
                                    "%#{params[:q]}%").to_json(:include => :referrer)
                                    }
    end
  end

  def new
    @category = Category.new
    if request.xhr?
      render partial: 'new_category_modal'
    end  
  end

  def create
    @category = Category.new(params[:category])
    flash[:success] = t('flash.category', message: t('flash.created')) if @category.save
    respond_with(@category)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def category_meth
    Category.all.map { |c| [c.name, c.id]  }
  end

  def build_tree()
    html = ""
    Category.root().each do |roots|
      html<< "\t<ul>\n"
      html<< "\t\t<li>\n"
      html<< "\t\t\t<span> <i  class='icon-arrow-down'></i> #{roots.name}</span>
                          <a href=# <i class= 'icon-minus-sign'></i></a>
                          <a href=# <i class= 'icon-plus-sign'></i></a> \n"
      html_son = ""
      html = html+ build_son(roots,html_son)
      html<< "\t\t</li>\n"
      html<< "\t</ul>\n"
    end
    html
  end

  def build_son(father, html)
      html<< "\t<ul>\n"
      father.referrals.each do |son|
        if son.referrals.empty?
          html<< "\t\t<li>\n"
          html<< "\t\t\t<span> <i class= 'icon-stop'></i> #{son.name}</span>
                              <a href=# <i class= 'icon-minus-sign'></i></a>
                              <a href=# <i class= 'icon-plus-sign'></i></a> \n"
          html<< "\t\t</li>\n"
        else
          html<< "\t\t<li>\n"
          html<< "\t\t\t<span> <i class= 'icon-arrow-down'></i> #{son.name}</span>
                              <a href=# <i class= 'icon-minus-sign'></i></a>
                              <a href=# <i class= 'icon-plus-sign'></i></a> \n"
          html_son = ""
          html= html +  build_son(son,html_son)
          html<< "\t\t</li>\n"
        end
      end
      html<< "\t</ul>\n"
      return html
  end


end

app/views/categories/_new_category_modal.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal", type: "button"} ×
      %h3= t('.new_category')
    = form_for(Category.new, remote: true, format: :json ) do |c|
      .modal-body
        .input
          = c.label :name
          = c.text_field :name, class: "pretty-input"
        .input
          = c.label t('.referrer_id')  
          .token_field 
            = c.text_field :referrer_id
      .modal-footer
        = c.submit t('.save'), class: "btn-modal-submit"

app/views/categories/_sub_header.html.haml
#categories
  .sub-header
    -if edit_or_new_page?(@category)
      %a.category-save
        %i.icon-save.icon-2x
        = t('sub_header.save')
      %a.category-danger{href: "#{categories_path}"}
        %i.icon-remove-sign.icon-2x
        = t('sub_header.cancel')
    -elsif show_page?(@category)
      %a.category-new{ href: "#{edit_category_path(@category)}" }
        %i.icon-edit.icon-2x
        = "editar"
    -else
      %a.category-new{ href: "#" ,id: "category-new"}
        %i.icon-plus-sign.icon-2x
        = t('sub_header.new')
      %a.category-print{href: "#"}
        %i.icon-print.icon-2x
        = t('sub_header.print')

app/views/categories/index.html.haml
#categories
  %ul.category-tabs
    %li.active
      %a{"data-toggle" => "tab", href: "#category-data"}
        = t('.category_data')
  .tree.well
    %ul
      %li
        %span
          %i.icon-arrow-down.icon-2x
          = t('.categories')
          %a{href: ""}
          =build_tree().html_safe

  #category-modal.modal.fade
    = render "new_category"